### ISSUE TITLE
API not working due to Cloudflare

### ISSUE THREAD

**Issue by RectalWorm** [theGordHoard/owo.vc#29]
![image](https://github.com/katlyn/owo.vc/assets/129939078/ce64dc6a-e2ac-4858-a781-f0bade9c484d)

**Comment by katlyn** [comment]
Some generic user-agents, such as the default user agent for the python requests library, have been blocked due to abuse. To resolve this, simply set a custom user agent on the request (preferably, include basic contact info so I can reach out to you in the future if needed for some reason). I have debated documenting which user agents are blocked but have decided against it for now, as it provides a small hurdle.
