### ISSUE TITLE
Sketchy link generator directs to incorrect destination

### ISSUE THREAD

**Issue by ChangelingSpy** [theGordHoard/owo.vc#7]
Sorry if this isn't the correct area to create an issue, I'm new to this.

Your "sketch" link generator at https://owo.vc/sketch generates links that all end up at a completely different website. It seems the IP address that is currently used in the links is no longer associated with your service.

Generating a link to https://example.org with your service results in http://0x2e65ae31/bIS1dIN7Mz:mfHGudHymMn:z[x== which ends up at [Fulbright Hungary's](http://46.101.174.49/bIS1dIN7Mz:mfHGudHymMn:z[x==) site.

This issue applies to all previously generated links. 

Thank you for the cool service!

**Comment by katlyn** [comment]
You would be correct, I no longer have control of the IP address. Unfortunately there's not much I can do at this point, but I'll remove the current feature as soon as I'm able to prevent more users from generating links. In addition, I'll add a link decoder to the current sketchy page just in case - I know it won't get much use to people who find the links, but it'll be something at least.

**Comment by katlyn** [comment]
I've removed the functionality in bee430b and added some notes to https://owo.vc/sketch. Sorry for the inconvenience, hopefully the rest of the service is still enjoyable to you. If you have any questions feel free to ask them, but I'll close this for now.

**Comment by katlyn** [comment]
Sketchy link generation has now been added back into owo.vc, though this time I've been smart enough to use a domain rather than an IP address. Links shortened with this new generator will look something like this: https://0x6f776f2e7663.net/spotify.com/hidden/_uafe5GPoUOd-6pf3PahbE20OoqhCXpv5hMwC7-ipWI. I hope that this will fit the niche that the old sketchy generator filled, while adding a bit more fun to it as well. If anyone would like to see how these links are generated, the relevant code is in [src/generators/sketchy.ts](https://github.com/katlyn/owo.vc/blob/owo/src/generators/sketchy.ts).
